kgu-capstone/study-with-me-be

- build.gradle
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/resources/application.yml
- 프로젝트 기본 Dependency 추가
- Spring Boot / Web / JPA / QueryDsl / JWT / Lombok / Test / REST Docs
- local/prod yml 설정 & test 전용 yml 설정
Closes #3
> [chore] 기본 프로젝트 설정을 진행한다

- src/main/java/com/kgu/studywithme/auth/exception/AuthErrorCode.java
- src/main/java/com/kgu/studywithme/auth/utils/AuthorizationExtractor.java
- src/main/java/com/kgu/studywithme/auth/utils/JwtTokenProvider.java
- src/main/java/com/kgu/studywithme/global/annotation/ExtractPayload.java
- src/main/java/com/kgu/studywithme/global/annotation/ExtractPayloadArgumentResolver.java
- src/main/java/com/kgu/studywithme/global/annotation/ExtractToken.java
- src/main/java/com/kgu/studywithme/global/annotation/ExtractTokenArgumentResolver.java
- src/main/java/com/kgu/studywithme/global/config/ArgumentResolverConfiguration.java
- src/main/java/com/kgu/studywithme/global/config/JpaAuditingConfiguration.java
- src/main/java/com/kgu/studywithme/global/config/QueryDslConfiguration.java
- src/test/java/com/kgu/studywithme/auth/utils/JwtTokenProviderTest.java
- JPA, QueryDsl 관련 설정 클래스 추가
- JWT 형식의 Token 관련 유틸성 클래스 구현 <code>JwtTokenProvider</code>
- HTTP Request Authorization Header로부터 Token & Token's Payload를 추출하는 유틸성 클래스 구현
- <code>AuthorizationExtractor</code>
- <code>@ExtractToken & ExtractTokenArgumentResolver</code>
- <code>@ExtractPayload & ExtractPayloadArgumentResolver</code>
Closes #8
> [feat] Token 기반 인증을 위한 기초 설계를 진행한다

- src/docs/asciidoc/token-reissue.adoc
- src/main/java/com/kgu/studywithme/auth/controller/TokenReissueApiController.java
- src/main/java/com/kgu/studywithme/auth/domain/Token.java
- src/main/java/com/kgu/studywithme/auth/domain/TokenRepository.java
- src/main/java/com/kgu/studywithme/auth/service/TokenManager.java
- src/main/java/com/kgu/studywithme/auth/service/TokenReissueService.java
- src/main/java/com/kgu/studywithme/auth/service/dto/response/TokenResponse.java
- src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
- src/test/java/com/kgu/studywithme/auth/domain/TokenRepositoryTest.java
- src/test/java/com/kgu/studywithme/auth/service/TokenManagerTest.java
- src/test/java/com/kgu/studywithme/auth/service/TokenReissueServiceTest.java
- src/test/java/com/kgu/studywithme/common/ControllerTest.java
- src/test/java/com/kgu/studywithme/common/DatabaseCleaner.java
- src/test/java/com/kgu/studywithme/common/RepositoryTest.java
- src/test/java/com/kgu/studywithme/common/ServiceTest.java
- src/test/java/com/kgu/studywithme/common/utils/TokenUtils.java
- Token Entity 설계
- Token 관리를 위한 <code>TokenManager & TokenRepositor</code> 구현 + 테스트 코드 작성
- Token 재발급을 위한 <code>TokenReissueService</code> 구현 및 재발급 엔드포인트 <code>POST /api/token/reissue</code> 구현
- 전체적인 Layer 테스트간 베이스가 되는 공통 클래스 추가
- Controller 테스트 -> <code>extends ControllerTest</code>
- @WebMvcTest
- Service 테스트 -> <code>extends ServiceTest</code>
- @SpringBootTest
- Repository 테스트 -> <code>extends RepositoryTest</code>
- @DataJpaTest
- <code>DirtiesContext</code> 제거를 위한 <code>DatabaseCleaner</code> 구현
Closes #11
> [feat] 토큰 관리에 대한 로직을 구현한다

- .gitignore
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-logging.yml
- src/main/resources/application-mapping.yml
- src/main/resources/application-prod.yml
- src/main/resources/application-test-datasource.yml
- src/main/resources/application.yml
- src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
- src/test/java/com/kgu/studywithme/auth/domain/TokenRepositoryTest.java
- src/test/java/com/kgu/studywithme/auth/service/TokenManagerTest.java
- src/test/java/com/kgu/studywithme/auth/service/TokenReissueServiceTest.java
- src/test/java/com/kgu/studywithme/auth/utils/JwtTokenProviderTest.java
- src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
- src/test/java/com/kgu/studywithme/member/domain/EmailTest.java
- src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
- src/test/java/com/kgu/studywithme/member/domain/PasswordTest.java
- <code>test / local / dev / prod</code> 각 환경에 따른 yml 설정 분리
- 테스트 코드에서 한글 제거
Closes #13
> [chore] 환경에 따른 설정을 분리한다

- build.gradle
- src/docs/asciidoc/oauth.adoc
- src/main/java/com/kgu/studywithme/auth/controller/OAuthApiController.java
- src/main/java/com/kgu/studywithme/auth/controller/dto/request/OAuthLoginRequest.java
- src/main/java/com/kgu/studywithme/auth/exception/AuthErrorCode.java
- src/main/java/com/kgu/studywithme/auth/exception/AuthRequestValidationMessage.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/GoogleOAuthConnector.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/GoogleOAuthUri.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/OAuthConnector.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/OAuthProperties.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/OAuthUri.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/dto/response/GoogleTokenResponse.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/dto/response/GoogleUserResponse.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/dto/response/OAuthTokenResponse.java
- src/main/java/com/kgu/studywithme/auth/infra/oauth/dto/response/OAuthUserResponse.java
- src/main/java/com/kgu/studywithme/auth/service/OAuthService.java
- src/main/java/com/kgu/studywithme/global/config/RestTemplateConfiguration.java
- src/main/java/com/kgu/studywithme/global/exception/ApiGlobalExceptionHandler.java
- src/main/java/com/kgu/studywithme/global/exception/StudyWithMeOAuthException.java
- src/main/resources/application-test.yml
- src/test/java/com/kgu/studywithme/auth/controller/AuthApiControllerTest.java
- src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
- src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
- src/test/java/com/kgu/studywithme/auth/controller/utils/OAuthLoginRequestUtils.java
- src/test/java/com/kgu/studywithme/auth/infra/oauth/OAuthUriTest.java
- src/test/java/com/kgu/studywithme/auth/service/OAuthServiceTest.java
- src/test/java/com/kgu/studywithme/common/ControllerTest.java
- src/test/java/com/kgu/studywithme/common/InfraTest.java
- src/test/java/com/kgu/studywithme/common/config/MockMvcConfiguration.java
- src/test/java/com/kgu/studywithme/common/utils/TokenUtils.java
- 테스트 전용 <code>application-test-external.yml</code> 분리
- Google OAuth 인증 로직 구현
- OAuth 요청 스펙 관련 <code>OAuthProperties</code>
- Authoriaton Code 요청을 위한 URI를 생성하는 <code>OAuthUri -> GoogleOAuthUri</code>
- 실제 Google Authorization Server와 통신을 위한 <code>OAuthConnector -> GoogleOAuthConnector</code>
- Google UserInfo에 따른 흐름 분기
- 이메일에 대해서 이미 사용자가 존재한다면 로그인 성공 후 토큰 발급
- 사용자가 존재하지 않으면 <code>GoogleUserResponse</code>의 값을 토대로 추가정보 기입 후 회원가입 진행
- 테스트 코드 작성
Closes #21
> [feat] 소셜 로그인 기능을 구현한다

- .github/workflows/backend-ci.yml
- .gitignore
- Github Actions를 통한 CI 자동화 구현
- Github Actions CI 작업 도중 <code>.gitignore에 포함된 yml</code>로 인해 에러 발생
- <code>Git Submodule</code>을 연동해서 .gitignore yml 옮기기
Closes #27
> [chore] CI(Continuous Integration) 환경을 구축한다

- .github/workflows/backend-ci.yml
- src/docs/asciidoc/category.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/com/kgu/studywithme/category/controller/CategoryApiController.java
- src/main/java/com/kgu/studywithme/category/service/CategoryService.java
- src/main/java/com/kgu/studywithme/category/service/dto/response/CategoryResponse.java
- src/test/java/com/kgu/studywithme/category/controller/CategoryApiControllerTest.java
- src/test/java/com/kgu/studywithme/category/service/CategoryServiceTest.java
- src/test/java/com/kgu/studywithme/common/ControllerTest.java
- 전체 카테고리 조회 API 구현
- 테스트 코드 작성
Closes #30
> [feat] 전체 카테고리 조회 API를 구현한다

- .github/workflows/backend-ci.yml
- CI Test action 수정
Closes #32
> [chore] CI 테스트 결과에 대한 action을 수정한다

- .gitignore
- Git Submodule 제거에 따른 private yml 파일 추가 -> .gitignore 추가
Closes #34
> [chore] Git Submodule 및 Github Actions CI 제거

- src/main/java/com/kgu/studywithme/auth/controller/OAuthApiController.java
- src/main/java/com/kgu/studywithme/auth/service/OAuthService.java
- src/main/java/com/kgu/studywithme/auth/service/dto/response/LoginResponse.java
- src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
- src/test/java/com/kgu/studywithme/auth/service/OAuthServiceTest.java
- TokenResponse -> LoginResponse 변경
- 테스트 코드 수정
Closes #46
> [refactor] 로그인 성공 시 응답 스펙을 수정한다

- src/main/java/com/kgu/studywithme/global/config/RestTemplateConfiguration.java
- RestTemplate 빈 설정 수정
Closes #49
> [refactor] RestTemplate 빈 설정을 수정한다

- src/main/java/com/kgu/studywithme/global/annotation/ExtractPayloadArgumentResolver.java
- src/main/java/com/kgu/studywithme/global/annotation/ExtractTokenArgumentResolver.java
- src/main/java/com/kgu/studywithme/global/config/AdditionalWebConfiguration.java
- src/main/java/com/kgu/studywithme/global/interceptor/TokenValidityInterceptor.java
- src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
- src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
- JWT Token의 유효성 검증을 Annotation Level이 아닌 <code>Spring Interceptor</code>에서 진행하도록 수정
Closes #52
> [refactor] JWT Token에 대한 유효성 검사를 Spring Interceptor에서 진행하도록 수정한다

- src/main/java/com/kgu/studywithme/global/config/AdditionalWebConfiguration.java
- src/main/java/com/kgu/studywithme/global/interceptor/TokenValidityInterceptor.java
- CORS 설정 추가
- <code>Preflight Request</code>에 대한 TokenValidityInterceptor 로직 추가
Closes #58
> [feat] CORS 설정을 추가한다

- src/main/java/com/kgu/studywithme/global/BaseEntity.java
- src/main/java/com/kgu/studywithme/member/domain/Member.java
- 생성/수정 시간에 대한 필드를 포함한 <code>@MappedSuperclass BaseEntity</code> 구현
Closes #62
> [feat] 생성/수정 시간과 관련된 필드를 포함한 BaseEntity를 구현한다

- src/main/java/com/kgu/studywithme/auth/service/dto/response/MemberInfo.java
- src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
- src/main/java/com/kgu/studywithme/member/domain/Member.java
- src/main/java/com/kgu/studywithme/member/domain/RealProfile.java
- src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
- src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
- 사용자가 Google 프로필 이미지를 수정했을 경우 본 서비스에도 반영하기 위한 로직 추가
Closes #69
> [fix] 구글 프로필 이미지가 업데이트 된 경우 서비스상에서 업데이트 되지 않는 이슈를 수정한다

- src/main/java/com/kgu/studywithme/category/exception/CategoryErrorCode.java
- src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/domain/StudyArea.java
- src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
- src/main/resources/application-dev.yml
- src/test/java/com/kgu/studywithme/fixture/StudyFixture.java
- src/test/java/com/kgu/studywithme/study/domain/StudyAreaTest.java
- src/test/java/com/kgu/studywithme/study/domain/StudyRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
- src/test/java/com/kgu/studywithme/study/domain/assignment/AssignmentTest.java
- src/test/java/com/kgu/studywithme/study/domain/assignment/AssignmentsTest.java
- src/test/java/com/kgu/studywithme/study/domain/assignment/submit/SubmitTest.java
- src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceTest.java
- src/test/java/com/kgu/studywithme/study/domain/notice/NoticeTest.java
- src/test/java/com/kgu/studywithme/study/domain/notice/comment/CommentTest.java
- src/test/java/com/kgu/studywithme/study/domain/participant/ParticipantTest.java
- src/test/java/com/kgu/studywithme/study/domain/participant/ParticipantsTest.java
- src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
- 오프라인 스터디 진행 지역에 대한 필드 추가
Closes #72
> [refactor] 오프라인 스터디 진행 지역에 대한 필드를 추가한다

- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/domain/participant/Participants.java
- src/main/java/com/kgu/studywithme/study/domain/review/Review.java
- src/main/java/com/kgu/studywithme/study/domain/review/ReviewRepository.java
- src/main/java/com/kgu/studywithme/study/domain/review/Reviews.java
- src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
- src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
- src/test/java/com/kgu/studywithme/study/domain/assignment/AssignmentsTest.java
- src/test/java/com/kgu/studywithme/study/domain/review/ReviewTest.java
- src/test/java/com/kgu/studywithme/study/domain/review/ReviewsTest.java
- 스터디 졸업생들이 리뷰를 작성하기 위한 Review Entity 설계
- 테스트 코드
Closes #78
> [feat] 스터디 종료 시 작성할 수 있는 Review를 설계한다

- src/docs/asciidoc/study-register.adoc
- src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
- src/main/java/com/kgu/studywithme/member/domain/Member.java
- src/main/java/com/kgu/studywithme/member/domain/interest/Interest.java
- src/main/java/com/kgu/studywithme/member/domain/interest/InterestRepository.java
- src/main/java/com/kgu/studywithme/study/controller/StudyApiController.java
- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/domain/hashtag/Hashtag.java
- src/main/java/com/kgu/studywithme/study/domain/hashtag/HashtagRepository.java
- src/main/java/com/kgu/studywithme/study/service/StudyRegisterService.java
- src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
- src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/controller/utils/StudyRegisterRequestUtils.java
- src/test/java/com/kgu/studywithme/study/domain/StudyRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyRegisterServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyValidatorTest.java
- @ElementCollection 관계를 Entity 관계로 수정
- Member - Interest
- Study - Hashtag
Closes #83
> [refactor] @ElementCollection을 Entity 관계로 수정한다

- .github/workflows/backend-ci.yml
> #87 PR에 대해서 2023/03/30 Github Status 에러가 발생해서 제거했던 부분 롤백
> [feat] Github Actions Workflows CI 작업을 추가한다 (Retry)

- src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyCategorySearchRequest.java
- src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyRecommendSearchRequest.java
- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/domain/participant/Participants.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/utils/StudyCategoryCondition.java
- src/main/java/com/kgu/studywithme/study/utils/StudyRecommendCondition.java
- src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
- src/test/java/com/kgu/studywithme/study/domain/participant/ParticipantsTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
- 온라인 or 오프라인 조건에 온라인 + 오프라인 통합 조건 추가
- 팀장 권한 위임 시 기존 팀장이 아예 제거되는 오류 수정
Closes #101
> [refactor & fix] 메인페이지 스터디 조회 타입에 온/오프 통합을 추가한다

- src/main/java/com/kgu/studywithme/auth/service/dto/response/MemberInfo.java
- src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
- src/main/java/com/kgu/studywithme/member/domain/Member.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/StudyHost.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/StudyReviewer.java
- src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
- src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
- src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/controller/utils/SignUpRequestUtils.java
- src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
- Member 도메인 profileUrl 필드 제거
Closes #102
> [refactor] 사용자 프로필 이미지 생성 방식 수정에 의해서 profileUrl을 제거한다

- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/member-information.adoc
- src/main/java/com/kgu/studywithme/global/annotation/ValidMember.java
- src/main/java/com/kgu/studywithme/global/annotation/ValidMemberAspect.java
- src/main/java/com/kgu/studywithme/global/config/AopConfiguration.java
- src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
- src/main/java/com/kgu/studywithme/member/domain/MemberRepository.java
- src/main/java/com/kgu/studywithme/member/service/MemberFindService.java
- src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
- src/main/java/com/kgu/studywithme/member/service/dto/response/MemberInformation.java
- src/main/java/com/kgu/studywithme/member/service/dto/response/RelatedStudy.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/SimpleStudy.java
- src/test/java/com/kgu/studywithme/common/ControllerTest.java
- src/test/java/com/kgu/studywithme/common/config/TestAopConfiguration.java
- src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
- src/test/java/com/kgu/studywithme/study/domain/assignment/PeriodTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
- 사용자 기본 정보 조회 API 구현
- 참여중인 스터디 & 졸업한 스터디 & 찜한 스터디 조회 API 구현
- 테스트 코드
> 조회 로직 간 <code>AOP Aspect</code>를 통한 PathVariable memberId와 Token Payload Id 일치 검증
Closes #99
> [feat] 마이페이지 사용자 관련 API를 구현한다

- src/docs/asciidoc/member-information.adoc
- src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
- src/main/java/com/kgu/studywithme/member/domain/review/PeerReviewRepository.java
- src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
- src/main/java/com/kgu/studywithme/member/service/dto/response/PeerReviewAssembler.java
- src/main/java/com/kgu/studywithme/study/controller/StudyInformationApiController.java
- src/main/java/com/kgu/studywithme/study/controller/attendance/AttendanceApiController.java
- src/test/java/com/kgu/studywithme/common/ServiceTest.java
- src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewRepositoryTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
- 사용자 피어리뷰 조회 API 구현
- 테스트 코드 작성
Closes #124
> [feature] 사용자별 피어리뷰 조회 API를 구현한다

- src/docs/asciidoc/study-weekly.adoc
- src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyWeeklyRequest.java
- src/main/java/com/kgu/studywithme/study/controller/dto/request/WeeklyAssignmentSubmitRequest.java
- src/main/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiController.java
- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/domain/attendance/AttendanceRepository.java
- src/main/java/com/kgu/studywithme/study/domain/week/Period.java
- src/main/java/com/kgu/studywithme/study/domain/week/Week.java
- src/main/java/com/kgu/studywithme/study/domain/week/WeekRepository.java
- src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
- src/main/java/com/kgu/studywithme/study/service/week/StudyWeeklyService.java
- src/main/java/com/kgu/studywithme/upload/controller/ImageUploadApiController.java
- src/test/java/com/kgu/studywithme/category/service/CategoryServiceTest.java
- src/test/java/com/kgu/studywithme/common/ControllerTest.java
- src/test/java/com/kgu/studywithme/fixture/WeekFixture.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/controller/utils/StudyWeeklyRequestUtils.java
- src/test/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
- src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/domain/week/PeriodTest.java
- src/test/java/com/kgu/studywithme/study/domain/week/WeekRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/domain/week/WeekTest.java
- src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyReviewServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
- 스터디 주차 등록 API 구현
- 주차별 과제 제출 API 구현
- 테스트 코드
Closes #126
> [feat] 스터디 주차 등록 및 주차별 과제 제출 API를 구현한다

- src/docs/asciidoc/image-upload.adoc
- src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/upload/controller/UploadApiController.java
- src/test/java/com/kgu/studywithme/common/ControllerTest.java
- src/test/java/com/kgu/studywithme/fixture/AttachmentFixture.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
- src/test/java/com/kgu/studywithme/upload/controller/UploadApiControllerTest.java
- 스터디 과제 제출자에 대한 `inner join -> left join`
- ImageUploadApiController -> UploadApiController
Closes #147
> [fix] 스터디 각 주차별 조회시 첨부파일이나 과제 제출자가 없을 경우 조회가 안되는 문제를 해결한다

- build.gradle
- src/main/java/com/kgu/studywithme/global/exception/ApiGlobalExceptionHandler.java
- src/main/java/com/kgu/studywithme/global/slack/SlackMetadata.java
- src/main/resources/application-test.yml
> [feat] 서버 API 예외에 대한 Slack API 알림 기능을 구현한다

- src/docs/asciidoc/member-information.adoc
- src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
- src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepository.java
- src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/member/infra/query/dto/response/AttendanceRatio.java
- src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
- src/main/java/com/kgu/studywithme/member/service/dto/response/AttendanceRatioAssembler.java
- src/main/java/com/kgu/studywithme/member/service/dto/response/MemberInformation.java
- src/main/java/com/kgu/studywithme/study/domain/attendance/AttendanceStatus.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
- src/test/java/com/kgu/studywithme/global/annotation/validation/ValidHashtagCountValidatorTest.java
- src/test/java/com/kgu/studywithme/global/annotation/validation/ValidImageExtensionValidatorTest.java
- src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
- src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceStatusTest.java
- 출석률 조회 API 구현
- 테스트 코드 작성
Closes #154
> [feat] 사용자 출석률 조회에 대한 API를 구현한다

- src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicStudy.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/NoticeInformation.java
- src/main/java/com/kgu/studywithme/study/service/StudySearchService.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
- 스터디 해시태그 쿼리 최적화
- 찜한 사용자 ID 리스트를 응답 스펙에 추가
- 테스트 코드 수정
Closes #156
> [refactor] 메인페이지 스터디 조회 쿼리 최적화를 진행한다

- src/main/java/com/kgu/studywithme/study/domain/StudyThumbnail.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicStudy.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/SimpleStudy.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/StudyInformation.java
- src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
- StudyImage enum에 고유 색상을 위한 필드 추가
- 테스트 코드 보완
Closes #161
> [refactor] 스터디 각 썸네일에 대한 고유 색상 필드를 추가한다

- src/docs/asciidoc/member-information.adoc
- src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
- src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
- src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
- 신청 대기상태인 스터디 리스트 조회 API 구현
- 테스트 코드
Closes #160
> [feat] 마이페이지에서 신청 대기 상태인 스터디 리스트를 조회하기 위한 API를 구현한다

- src/docs/asciidoc/study-update.adoc
- src/main/java/com/kgu/studywithme/study/controller/StudyApiController.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/service/StudyService.java
- src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyServiceTest.java
- 스터디 종료 API 구현
- 메인페이지 스터디 조회 쿼리에 종료에 대한 조건 추가
- 테스트 코드 작성 및 보완
Closes #164
> [feat] 스터디 종료 API를 구현한다

- src/main/java/com/kgu/studywithme/member/domain/Score.java
- src/test/java/com/kgu/studywithme/member/domain/MemberRepositoryTest.java
- src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
- src/test/java/com/kgu/studywithme/member/domain/ScoreTest.java
- src/test/java/com/kgu/studywithme/study/service/attendance/AttendanceServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
- 사용자 점수 메커니즘 수정
- 테스트 코드 수정 및 보완
> 기본값 = 80
> - 출석 = +1
> - 지각 = -1
> - 결석 = -5
Closes #173
> [refactor] 사용자 점수 메커니즘을 수정한다

- .gitignore
- src/docs/asciidoc/member-information.adoc
- src/main/java/com/kgu/studywithme/favorite/domain/FavoriteRepository.java
- src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
- src/main/java/com/kgu/studywithme/member/infra/query/dto/response/AttendanceRatio.java
- src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
- src/main/java/com/kgu/studywithme/study/domain/notice/comment/CommentRepository.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
- src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
- src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
- 사용자 정보와 관련된 API 접근 권한 수정
- 테스트 코드 수정
Closes #175
> [refactor] Private 마이페이지 정보와 Public 상대방 정보 간의 API 접근 권한을 수정한다

- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/service/StudyService.java
- src/test/java/com/kgu/studywithme/fixture/StudyFixture.java
- Study 생성 정적 팩토리 메소드에서 StudyType 파라미터 제거
Closes #181
> [refactor] 타입에 따른 Study 생성 정적 팩토리 메소드 인자를 수정한다

- src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/controller/StudySearchApiController.java
- src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyCategorySearchRequest.java
- src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyRecommendSearchRequest.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/utils/validator/ValidSearchSortType.java
- src/main/java/com/kgu/studywithme/study/utils/validator/ValidSearchSortTypeValidator.java
- src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/utils/validator/ValidSearchSortTypeValidatorTest.java
- 공지사항 조회에 `studyId`에 대한 where 조건 추가
- 메인페이지 스터디 조회 시 정렬 타입에 대한 `ValidSearchSortType` 구현
Closes #183
> [fix] 공지사항 조회 관련 버그를 수정한다

- src/docs/asciidoc/study-update.adoc
- src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyRegisterRequest.java
- src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyUpdateRequest.java
- src/main/java/com/kgu/studywithme/study/domain/GraduationPolicy.java
- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/domain/StudyRepository.java
- src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
- src/main/java/com/kgu/studywithme/study/service/ParticipationService.java
- src/main/java/com/kgu/studywithme/study/service/StudyFindService.java
- src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
- src/main/java/com/kgu/studywithme/study/service/StudyReviewService.java
- src/main/java/com/kgu/studywithme/study/service/StudyService.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/ParticipantInformation.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/StudyInformation.java
- src/test/java/com/kgu/studywithme/fixture/StudyFixture.java
- src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/controller/utils/StudyUpdateRequestUtils.java
- src/test/java/com/kgu/studywithme/study/domain/GraduationPolicyTest.java
- src/test/java/com/kgu/studywithme/study/domain/StudyRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
- src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyFindServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
- 스터디 졸업 요건 수정횟수 3회 제한으로 수정
- 전체적인 쿼리 최적화
- 테스트 코드 보완
Closes #185
> [refactor] 졸업요건 수정 횟수 제한 및 쿼리 최적화를 진행한다

- src/docs/asciidoc/study-weekly.adoc
- src/main/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiController.java
- src/main/java/com/kgu/studywithme/study/domain/week/Weekly.java
- src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/service/scheduler/StudyAttendanceScheduler.java
- src/main/java/com/kgu/studywithme/study/service/week/StudyWeeklyService.java
- src/test/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
- src/test/java/com/kgu/studywithme/study/domain/week/WeeklyTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
- 참여자 조회 Query 조건 추가
- 주차 생성 간 Sequential 검증 추가
- 테스트 코드 수정 및 보완
Closes #188
> [bug & refactor] API 오류 수정 및 주차 생성 관련 검증을 추가한다

- src/docs/asciidoc/member-signup.adoc
- src/main/java/com/kgu/studywithme/member/controller/MemberApiController.java
- src/main/java/com/kgu/studywithme/member/controller/dto/request/MemberUpdateRequest.java
- src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
- src/main/java/com/kgu/studywithme/member/domain/Member.java
- src/main/java/com/kgu/studywithme/member/domain/MemberRepository.java
- src/main/java/com/kgu/studywithme/member/domain/Region.java
- src/main/java/com/kgu/studywithme/member/service/MemberService.java
- src/main/java/com/kgu/studywithme/member/service/MemberValidator.java
- src/main/java/com/kgu/studywithme/study/service/ParticipationService.java
- src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
- src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/domain/MemberRepositoryTest.java
- src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
- src/test/java/com/kgu/studywithme/member/domain/RegionTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberServiceTest.java
- src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
- src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
- src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
- 이메일 수신 동의 flag 추가
- 사용자 정보 수정 API 구현
-테스트 코드 수정 및 보완
Closes #190
> [feat] 이메일 수신 동의를 추가 및 사용자 정보 수정 API를 구현한다

- src/main/java/com/kgu/studywithme/study/domain/StudyType.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/service/StudyService.java
- src/main/java/com/kgu/studywithme/study/utils/validator/ValidStudyTypeValidator.java
- src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/utils/validator/ValidStudyTypeValidatorTest.java
- StudyType Brief 네이밍 :: ON/OFF -> online/offline
Closes #193
> [refactor] StudyType에 대한 brief 네이밍을 수정한다

- src/docs/asciidoc/image-upload.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/com/kgu/studywithme/study/domain/Description.java
- src/main/java/com/kgu/studywithme/upload/controller/UploadApiController.java
- src/main/java/com/kgu/studywithme/upload/controller/dto/request/ImageUploadRequest.java
- src/main/java/com/kgu/studywithme/upload/utils/BucketMetadata.java
- src/main/java/com/kgu/studywithme/upload/utils/FileUploader.java
- src/main/java/com/kgu/studywithme/upload/utils/validator/ValidImageUploadType.java
- src/main/java/com/kgu/studywithme/upload/utils/validator/ValidImageUploadTypeValidator.java
- src/test/java/com/kgu/studywithme/fixture/AttachmentFixture.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/domain/DescriptionTest.java
- src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
- src/test/java/com/kgu/studywithme/upload/controller/UploadApiControllerTest.java
- src/test/java/com/kgu/studywithme/upload/utils/FileUploaderTest.java
- src/test/java/com/kgu/studywithme/upload/utils/validator/ValidImageUploadTypeValidatorTest.java
- 스터디 설명에 대한 별도 이미지 업로드 로직 구현
- 테스트 코드 수정
Closes #199
> [refactor] 스터디 생성 시 설명에 이미지를 추가할 수 있도록 수정한다

- src/main/java/com/kgu/studywithme/study/domain/week/submit/Submit.java
- src/main/java/com/kgu/studywithme/study/domain/week/submit/Upload.java
- `Upload -> uploadFileName & Submit -> Week`에 대한 JPA Column name 매칭 수정
Closes #201
> [refactor] JPA @Column name 매칭을 수정한다

- src/main/java/com/kgu/studywithme/study/domain/StudyThumbnail.java
- src/test/java/com/kgu/studywithme/study/domain/StudyThumbnailTest.java
> [refactor] 스터디 썸네일을 추가한다

- src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
- src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
- src/main/java/com/kgu/studywithme/member/service/dto/response/GraduatedStudy.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/SimpleGraduatedStudy.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/StudyReview.java
- src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
- 졸업한 스터디에 대한 리뷰 작성 여부 필드 추가
- 테스트 코드 수정
Closes #209
> [refactor] 졸업한 스터디에 대한 리뷰 작성 여부 필드를 응답에 추가한다

- src/docs/asciidoc/study-information.adoc
- src/main/java/com/kgu/studywithme/global/exception/ApiGlobalExceptionHandler.java
- src/main/java/com/kgu/studywithme/study/controller/StudyInformationApiController.java
- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/domain/StudyThumbnail.java
- src/main/java/com/kgu/studywithme/study/domain/participant/Participants.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/AttendanceInformation.java
- src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/AttendanceAssmbler.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/AttendanceSummary.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/StudyAttendanceMember.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/StudyParticipant.java
- src/main/java/com/kgu/studywithme/study/service/week/StudyWeeklyService.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/domain/week/submit/UploadAssignmentTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
- 스터디 출석부 응답에 대한 정보 수정
- 스터디 참여자 조회 API 구현
- 스터디 주차 첨부파일에 대한 NPE 오류 수정
- StudyThumbnail 이름 오타 수정
Closes #211
> [feat & refactor] 스터디 출석에 대한 응답 수정 및 참여자 조회 API를 구현한다

- src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/AttendanceAssmbler.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/StudyMemberAttendanceResult.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
- 응답 형식 `Map<StudyAttendanceMember, List<AttendanceSummary>> -> List<StudyMemberAttendanceResult>` 수정
Closes #213
> [refactor] 스터디 주차별 출석 정보 응답을 수정한다

- src/main/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiController.java
- src/main/java/com/kgu/studywithme/study/domain/attendance/Attendance.java
- src/main/java/com/kgu/studywithme/study/domain/week/submit/SubmitRepository.java
- src/main/java/com/kgu/studywithme/study/service/week/StudyWeeklyService.java
- src/test/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceTest.java
- src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
- 제출한 과제 수정 시 해당 주차 Period 기준으로 지각 판단 후 지각 패널티 추가
- 테스트 코드 보완
Closes #217
> [refactor] 제출 과제 수정 시 수정 시각 기준 지각 패널티를 추가한다

- .github/workflows/backend-cd.yml
- .github/workflows/backend-ci.yml
- build.gradle
- script/deploy.sh
- src/main/java/com/kgu/studywithme/auth/domain/TokenRepository.java
- src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/domain/StudyRepository.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicStudy.java
- src/main/resources/application-dev.yml
- src/main/resources/application-logging.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
- src/test/resources/application.yml
- 배포를 위한 Github Action workflows `backend-cd.yml` 작성
- 배포 스크립트 `deploy.sh` 작성
- yml 구조 수정
- local{default} / dev / prod
Closes #134
> [Infra] NCP Server 배포를 위한 Github Actions Workflows yml을 추가한다

- src/main/java/com/kgu/studywithme/study/domain/Study.java
- src/main/java/com/kgu/studywithme/study/domain/participant/ParticipantRepository.java
- src/main/java/com/kgu/studywithme/study/domain/participant/Participants.java
- src/main/java/com/kgu/studywithme/study/service/ParticipationService.java
- src/test/java/com/kgu/studywithme/study/domain/participant/ParticipantRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
- 스터디 팀장 위임 시 Participant Table에서 새로운 팀장이 제거되지 않는 버그 수정
Closes #221
> [fix] 스터디 팀장 위임 시 Participant Table에서 새로운 팀장이 제거되지 않는 버그를 해결한다

- src/docs/asciidoc/member-information.adoc
- src/docs/asciidoc/member-signup.adoc
- src/docs/asciidoc/oauth.adoc
- src/docs/asciidoc/study-information.adoc
- src/docs/asciidoc/study-review.adoc
- src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
- src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/domain/StudyThumbnail.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/AttendanceInformation.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/CommentInformation.java
- src/main/java/com/kgu/studywithme/study/infra/query/dto/response/ReviewInformation.java
- src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
- src/main/java/com/kgu/studywithme/study/service/dto/response/StudyMemberAttendanceResult.java
- src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
- src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
- src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
- 스터디 출석 정보 관련 쿼리 수정
- 특정 API에 대한 Token Required 해제
Closes #223
> [refactor] 스터디 출석 정보 관련 쿼리 수정 및 특정 API에 대한 Token Required를 해제한다
